spring:
  application:
    name: kraken-bot

kraken:
  url: https://api.kraken.com
  key: abc
  secret: def
  candlesInterval: 60
  sinceDays: 2

indicator:
  bbPeriod: 20
  bbStdDev: 2.0
  shortMA: 9
  longMA: 21
  macdFast: 12
  macdSlow: 26
  macdSignal: 9
  obvPeriod: 14

operation:
  minutesLimit: 90
  stop: 0.006
  profit: 0.018
  currency: USDZ
  notBelow: 100
  pairs:
    XXLM: ZUSD
    XXRP: ZUSD
    NEAR: USD
    FET: USD
    INJ: USD
    RENDER: USD
    RAY: USD
    1INCH: USD
    TRX: USD
    DENT: USD
    DOT: USD
    LINK: USD
    COMP: USD
    AAVE: USD
    MKR: USD