spring:
  application:
    name: kraken-bot

kraken:
  url: https://api.kraken.com
  key: abc
  secret: def

operation:
  pairs:
    XXLM: ZUSD
    XXRP: ZUSD
    NEAR: USD
    FET: USD
    INJ: USD
    RENDER: USD
    RAY: USD
    1INCH: USD
    TRX: USD
    DENT: USD
    DOT: USD
    LINK: USD
    COMP: USD
    AAVE: USD
    MKR: USD