spring:
  application:
    name: crypto-bot
bot:
  validationCron: "0 */5 * * * *"   #validate trade every five minutes
  newTradeCron: "0 */15 * * * *"    #check to open a new trade every 15 minutes

kraken:
  url: https://api.kraken.com
  key:
  secret:
  candlesInterval: 60 #minutes
  candlesSince: 5
  candlesSinceUnit: DAY #or minute

indicator:
  bbPeriod: 20
  bbStdDev: 2.0
  shortMA: 9
  longMA: 21
  macdFast: 12
  macdSlow: 26
  macdSignal: 9
  obvPeriod: 14

operation:
  minutesLimit: 90 #trade open time limit
  stop: 0.006    #stop loss
  profit: 0.018  #take profit
  currency: ZUSD
  notBelow: 500  #don't trade below
  operationFee: 0.0026
  pairs:
    XXLM: ZUSD
    XXRP: ZUSD
    NEAR: USD
    FET: USD
    INJ: USD
    RENDER: USD
    RAY: USD
    1INCH: USD
    TRX: USD
    DENT: USD
    DOT: USD
    LINK: USD
    COMP: USD
    AAVE: USD
    MKR: USD
    ENJ: USD